Threads
pasimann/lounasvahti pull request #4
Opened 2018-08-28 09:20 UTC by mehtis

Use threads instead of individual posts. Both when asking and for cronjobs.

2018-08-28 09:29 UTC, tanelih commented on src/index.ts
> +  threadStart().then(thread =>
Mieluummin ehkä tekisin ilman tällaista erillistä `threadStart` metodia ja laittaisin vain:

```javascript
slack.post(/* tähän ehkä päivämäärä? */)
  .then((thread) => Promise.all(places.map((p) => display(date, p, thread))
  .catch((err) => log.error(err.stack || err.message))
```

2018-08-28 09:43 UTC, tanelih requested changes
Vähän voisi jotain tässä iteroida.

2018-08-28 09:43 UTC, tanelih commented on src/index.ts
> +function display (date: Date, place: Place, thread?: string): Promise<SlackAPICallResult> {
Tässä näyttää välillä tuo thread olevan objekti, josta otetaan `.ts` ja välillä ihan suoraan string? Ehkäpä tehdään rajapinta seuraavanlaiseksi:

```typescript
interface IMessage {
  ts: string
}
async function displayLunchList (places: Place[], date: Date): Promise<void> {
  const message= await slack.post(/* tähän päivämäärä */)
  await Promise.all(places.map(async (place) => {
    await slack.post(/* tähän se per-paikka viesti */, message.ts)
  }))
}
```

Sitten tuolla `slack.ts` tiedostossa voidaan tehdä näin:

```typescript
public async post(message: string, ts?: string) {
  // ...
}
```

2018-08-28 09:43 UTC, tanelih commented on src/index.ts
> +  threadStart().then(thread =>
Kts. tuo alempi kommentti

2018-08-29 10:55 UTC, tanelih requested changes

2018-08-29 10:55 UTC, tanelih commented on src/cron.ts
>  import * as moment from 'moment-timezone'
Katsohan, onko siellä `tsconfig.json` tiedostossa se `esModuleInterop` päällä, voi ratkaista jos on jotain ongelmia importtaamisessa.

2018-08-29 10:55 UTC, tanelih commented on src/cron.ts
> +export async function createCronJob (params: { pattern: string, onTick: CronTickHandler, start?: boolean, timeZone?: string, runOnInit?: boolean}): Promise<CronJob> {
Tätä parametriobjektia voisi ehkä aukaista ihan omaksi pieneksi interfacekseen. Esim.

```typescript
interface ICronJobParams {
  pattern: string
  onTick: CronTickHandler
  // ...
}
```

2018-08-29 10:55 UTC, tanelih commented on src/slack.ts
> +    return this.webClient.chat.postMessage({ channel: this.options.channel, text: message, thread_ts: ts, ...options })
Palauttaako tämä muka `Promise` objektin?

EDIT: Palauttaa.
EDIT: Mielestäni tämän pitäisi ehkä olla ihan (tuon ylemmän kommentin mukaisesti):

```typescript
const response = await this.webClient.chat.postMessage(...)
return { ts: response.ts }
```

Toki jos tuosta `WebAPICallResult` tarvitaan jotain niin eri asia.

2018-08-29 10:55 UTC, tanelih commented on src/slack.ts
> +export interface IMessage extends WebAPICallResult {
Ei extendata, jos ei tehdä tuolla `WebAPICallResult` interfacella oikeastaan mitään. Eli jos ei ole tarvetta oikeasti palauttaa tuosta `post` funktiosta mitään muuta kuin tuo timestamp-arvo, niin tämähän on sitten ihan:

```typescript
interface IMessage { ts: string }
```

2018-08-29 10:55 UTC, tanelih commented on src/index.ts
> +    Promise.all(places.map((p: Place) => displayLunchLists(date, p, message.ts)))
Tämä sinun "try catch" blokki ei tee tässä mitään, jollet oikeasti "odota" tätä `Promise.all` palautuvaa arvoa (eli siis koosteista promisea).

```typescript
try {
  const message = ...
  await Promise.all(...)
} catch (err) {
  log.error(err)
}
```

2018-08-29 10:55 UTC, tanelih commented on src/index.ts
> +async function displayLunchLists (date: Date, place: Place, ts?: string): Promise<void> {
1. Kyseessä yhden paikan lounaslistan näyttäminen, joten tuo `displayLunchLists` nimi hieman erikoinen.
2. Parametrien järjestys mielestäni `(place, date, ts?)`.

2018-08-29 11:49 UTC, mehtis commented on src/index.ts
> +    Promise.all(places.map((p: Place) => displayLunchLists(date, p, message.ts)))
Tämä mietityttikin että kaipaako await vai ei.

2018-08-30 06:06 UTC, tanelih approved these changes
Hyvin teit.

2018-08-30 06:15 UTC, merged